[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = {Path = ["/*"]}

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.jsx"
    [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.mjs"
    [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/src/*"
    [headers.values]
    Content-Type = "application/javascript; charset=utf-8" 